export interface MenuItem {
  id: string;
  name: string;
  category: 'starters' | 'main' | 'indian' | 'asian' | 'desserts' | 'beverages';
  isVeg: boolean;
  isChefSpecial?: boolean;
  price: number;
  description: string;
  imageUrl: string;
  portion: string;
  spiceLevel?: 'Mild' | 'Medium' | 'Spicy';
  tags: string[];
}

export const MENU_CATEGORIES = [
  { id: 'all', label: 'All Creations' },
  { id: 'starters', label: 'Starters & Platters' },
  { id: 'indian', label: 'Indian & Tandoor' },
  { id: 'asian', label: 'Chinese & Asian' },
  { id: 'main', label: 'Mains & Curries' },
  { id: 'desserts', label: 'Artisanal Desserts' },
  { id: 'beverages', label: 'Cocktails & Sips' },
] as const;

export const MENU_ITEMS: MenuItem[] = [
  // Starters
  {
    id: 'starter-1',
    name: 'Truffle Malai Paneer Tikka',
    category: 'starters',
    isVeg: true,
    isChefSpecial: true,
    price: 385,
    description: 'Fresh cottage cheese marinated in creamy cashew, cardamom, and subtle black truffle oil, char-grilled in our clay tandoor.',
    imageUrl: '/images/food_paneer_tikka_1790785314249.jpg',
    portion: 'Serves 2',
    spiceLevel: 'Mild',
    tags: ['Clay Oven', 'Creamy', 'Signature'],
  },
  {
    id: 'starter-2',
    name: 'Bhatti Ka Murgh Tikka',
    category: 'starters',
    isVeg: false,
    isChefSpecial: true,
    price: 445,
    description: 'Boneless tender chicken steeped in crushed spices, roasted gram flour, and mustard oil, charred to smoky perfection.',
    imageUrl: '/images/food_tandoori_chicken_1790785330830.jpg',
    portion: '6 Pieces',
    spiceLevel: 'Spicy',
    tags: ['Smoky', 'Clay Oven', 'Popular'],
  },
  {
    id: 'starter-3',
    name: 'Crispy Water Chestnut & Lotus Stem',
    category: 'starters',
    isVeg: true,
    price: 360,
    description: 'Honey-chilli tossed crunchy lotus roots and water chestnuts with toasted sesame seeds and fresh scallions.',
    imageUrl: '/images/hero_gourmet_dining_1790782920279.jpg',
    portion: 'Serves 2',
    spiceLevel: 'Medium',
    tags: ['Crisp', 'Oriental Glaze'],
  },
  {
    id: 'starter-4',
    name: 'Butter Garlic Herb Prawns',
    category: 'starters',
    isVeg: false,
    isChefSpecial: true,
    price: 520,
    description: 'Tiger prawns pan-tossed in clarified herb butter, roasted garlic flakes, and a dash of white wine reduction.',
    imageUrl: '/images/hero_cocktail_sunset_1790782906080.jpg',
    portion: '5 Jumbo Pieces',
    spiceLevel: 'Mild',
    tags: ['Seafood', 'Garlic Glaze'],
  },

  // Indian
  {
    id: 'ind-1',
    name: 'Upper Deck Royal Dal Makhani',
    category: 'indian',
    isVeg: true,
    isChefSpecial: true,
    price: 360,
    description: 'Slow-simmered black urad lentils cooked overnight on tandoor embers with organic churned butter and vine-ripened tomatoes.',
    imageUrl: '/images/food_butter_chicken_1790785348385.jpg',
    portion: 'Serves 2',
    spiceLevel: 'Mild',
    tags: ['Slow Cooked', 'Heritage Recipe'],
  },
  {
    id: 'ind-2',
    name: 'Old Delhi Butter Chicken',
    category: 'indian',
    isVeg: false,
    isChefSpecial: true,
    price: 475,
    description: 'Succulent shredded tandoori chicken cooked in a velvet satin tomato makhani gravy enriched with kasoori methi.',
    imageUrl: '/images/food_butter_chicken_1790785348385.jpg',
    portion: 'Serves 2',
    spiceLevel: 'Medium',
    tags: ['Rich Gravy', 'House Favorite'],
  },
  {
    id: 'ind-3',
    name: 'Paneer Lababdar Awadhi',
    category: 'indian',
    isVeg: true,
    price: 410,
    description: 'Cottage cheese chunks cooked in an onion-tomato concasse with grated paneer and freshly toasted whole coriander.',
    imageUrl: '/images/food_paneer_tikka_1790785314249.jpg',
    portion: 'Serves 2',
    spiceLevel: 'Medium',
    tags: ['Awadhi Style', 'Hearty'],
  },
  {
    id: 'ind-4',
    name: 'Kashmiri Mutton Rogan Josh',
    category: 'indian',
    isVeg: false,
    price: 540,
    description: 'Tender baby mutton braised slowly with aromatic ratan jot root, fennel, dry ginger, and Kashmiri red chillies.',
    imageUrl: '/images/food_butter_chicken_1790785348385.jpg',
    portion: 'Serves 2',
    spiceLevel: 'Medium',
    tags: ['Slow Braised', 'Kashmiri'],
  },

  // Asian
  {
    id: 'asian-1',
    name: 'Steamed Edamame & Truffle Dim Sum',
    category: 'asian',
    isVeg: true,
    isChefSpecial: true,
    price: 395,
    description: 'Handcrafted translucent dumpling skins packed with crushed edamame, water chestnut, and infused with white truffle essence.',
    imageUrl: '/images/food_steamed_dimsums_1790785377549.jpg',
    portion: '5 Pieces',
    spiceLevel: 'Mild',
    tags: ['Handcrafted', 'Steamed', 'Truffle'],
  },
  {
    id: 'asian-2',
    name: 'Wok-Tossed Kung Pao Chicken',
    category: 'asian',
    isVeg: false,
    price: 440,
    description: 'Diced chicken tossed with dry Sichuan chillies, roasted crunchy peanuts, bell peppers, and savoury soy-vinegar glaze.',
    imageUrl: '/images/food_tandoori_chicken_1790785330830.jpg',
    portion: 'Serves 2',
    spiceLevel: 'Medium',
    tags: ['Sichuan', 'Wok Hei'],
  },
  {
    id: 'asian-3',
    name: 'Burnt Garlic Hakka Noodles',
    category: 'asian',
    isVeg: true,
    price: 320,
    description: 'Classic wok-charred wheat noodles tossed with shredded garden greens, spring onion, and golden crisp garlic slivers.',
    imageUrl: '/images/hero_gourmet_dining_1790782920279.jpg',
    portion: 'Serves 2',
    spiceLevel: 'Mild',
    tags: ['Wok Fresh', 'All Time Classic'],
  },
  {
    id: 'asian-4',
    name: 'Chilli Coriander Pan-Fried Fish',
    category: 'asian',
    isVeg: false,
    isChefSpecial: true,
    price: 495,
    description: 'Fresh river sole fillets pan-seared with fresh coriander paste, bird’s eye chillies, and light lemon zest.',
    imageUrl: '/images/hero_gourmet_dining_1790782920279.jpg',
    portion: 'Serves 2',
    spiceLevel: 'Spicy',
    tags: ['Pan Seared', 'Fresh Catch'],
  },

  // Mains
  {
    id: 'main-1',
    name: 'Dum Pukht Chicken Biryani',
    category: 'main',
    isVeg: false,
    isChefSpecial: true,
    price: 460,
    description: 'Long grain aged basmati rice layered with spiced marinated chicken, saffron milk, and browned onions, sealed in clay pot.',
    imageUrl: '/images/food_dum_biryani_1790785360650.jpg',
    portion: 'With Burani Raita',
    spiceLevel: 'Medium',
    tags: ['Clay Pot Dum', 'Aged Basmati'],
  },
  {
    id: 'main-2',
    name: 'Subz Nizami Handi Biryani',
    category: 'main',
    isVeg: true,
    price: 390,
    description: 'Garden vegetables, paneer cubes, and aromatic saffron basmati dum cooked with rose water and whole roasted spices.',
    imageUrl: '/images/food_dum_biryani_1790785360650.jpg',
    portion: 'With Mirchi Ka Salan',
    spiceLevel: 'Medium',
    tags: ['Fragrant', 'Traditional'],
  },
  {
    id: 'main-3',
    name: 'Artisanal Bread Basket',
    category: 'main',
    isVeg: true,
    price: 240,
    description: 'Assortment of Butter Naan, Garlic Naan, Laccha Paratha, and Missi Roti fresh off the tandoor.',
    imageUrl: '/images/hero_gourmet_dining_1790782920279.jpg',
    portion: '4 Assorted Breads',
    spiceLevel: 'Mild',
    tags: ['Tandoor Baked', 'Warm'],
  },

  // Desserts
  {
    id: 'des-1',
    name: 'Sizzling Sky Brownie with Belgian Chocolate',
    category: 'desserts',
    isVeg: true,
    isChefSpecial: true,
    price: 320,
    description: 'Warm walnut fudge brownie served on a cast-iron sizzler with rich Belgian chocolate ganache and vanilla bean gelato.',
    imageUrl: '/images/food_sizzling_brownie_1790785390437.jpg',
    portion: 'Serves 2',
    tags: ['Sizzling', 'Decadent'],
  },
  {
    id: 'des-2',
    name: 'Baked Biscoff & Saffron Cheesecake',
    category: 'desserts',
    isVeg: true,
    isChefSpecial: true,
    price: 350,
    description: 'Silky smooth baked Philadelphia cheesecake infused with saffron and layered over crunchy spiced Lotus Biscoff crumb.',
    imageUrl: '/images/food_sizzling_brownie_1790785390437.jpg',
    portion: 'Single Slice',
    tags: ['Gourmet', 'Signature'],
  },
  {
    id: 'des-3',
    name: 'Royal Kesari Rasmalai Mousse',
    category: 'desserts',
    isVeg: true,
    price: 280,
    description: 'Velvety cardamom-infused sponge soaked in rich saffron milk, topped with pistachio flakes and dried rose petals.',
    imageUrl: '/images/food_paneer_tikka_1790785314249.jpg',
    portion: 'Serves 1-2',
    tags: ['Classic Twist', 'Pistachio'],
  },

  // Beverages
  {
    id: 'bev-1',
    name: 'Upper Deck Smoked Old Fashioned',
    category: 'beverages',
    isVeg: true,
    isChefSpecial: true,
    price: 495,
    description: 'Premium bourbon infused with orange bitters and demerara sugar, smoked live in applewood oak smoke under a glass dome.',
    imageUrl: '/images/hero_cocktail_sunset_1790782906080.jpg',
    portion: 'Signature Cocktail',
    tags: ['Craft Mixology', 'Smoky Oak'],
  },
  {
    id: 'bev-2',
    name: 'Seawoods Sunset Passion Spritz',
    category: 'beverages',
    isVeg: true,
    isChefSpecial: true,
    price: 450,
    description: 'Aperol, sparkling wine, fresh passion fruit puree, and club soda served over crystal ice with dehydrated citrus.',
    imageUrl: '/images/hero_cocktail_sunset_1790782906080.jpg',
    portion: 'Spritz Goblet',
    tags: ['Golden Hour', 'Refreshing'],
  },
  {
    id: 'bev-3',
    name: 'Electric Blue Lagoon Mocktail',
    category: 'beverages',
    isVeg: true,
    price: 260,
    description: 'Blue curacao essence, freshly squeezed Persian lime, mint sprigs, and effervescent fizz. Perfect non-alcoholic cooler.',
    imageUrl: '/images/hero_cocktail_sunset_1790782906080.jpg',
    portion: 'Tall Glass',
    tags: ['Zero Alcohol', 'Citrus Fresh'],
  },
  {
    id: 'bev-4',
    name: 'Espresso Martini Sky Edition',
    category: 'beverages',
    isVeg: true,
    price: 480,
    description: 'Fresh pulled dark espresso roast, vodka, and coffee liqueur shaken hard and crowned with chocolate dusted foam.',
    imageUrl: '/images/hero_cocktail_sunset_1790782906080.jpg',
    portion: 'Coupe Glass',
    tags: ['Night Owl', 'Rich Arabica'],
  },
];
